on:
  release:
    types: [published]

name: r-wasm/actions - image

jobs:
   release-file-system-image:
    uses: r-wasm/actions/.github/workflows/release-file-system-image.yml@v2
    with:
      packages: cli, data.table
      strip: c("demo", "doc", "examples", "help", "html", "include", "tests", "vignette")
    permissions:
      contents: write
      repository-projects: read
