on:
  release:
    types: [published]

name: r-wasm/actions - image

jobs:
   release-file-system-image:
    uses: r-wasm/actions/.github/workflows/release-file-system-image.yml@v2
    with:
      packages: evaluate,
                xfun,
                highr,
                yaml,
                knitr,
                tinytex,
                rmarkdown,
                htmlwidgets,
                lazyeval,
                crosstalk,
                DT,
                R.methodsS3,
                R.oo,
                R.utils,
                RColorBrewer,
                countrycode,
                gtable,
                isoband,
                MASS,
                lattice,
                nlme,
                Matrix,
                mgcv,
                farver,
                labeling,
                colorspace,
                munsell,
                viridisLite,
                scales,
                fansi,
                utf8,
                vctrs,
                pillar,
                pkgconfig,
                tibble,
                ggplot2,
                cowplot,
                data.table,
                fontBitstreamVera,
                fontLiberation,
                fontquiver,
                systemfonts,
                gdtools,
                sys,
                askpass,
                openssl,
                textshaping,
                ragg,
                uuid,
                xml2,
                zip,
                officer,
                flextable,
                ggh4x,
                purrr,
                ggiraph,
                generics,
                timechange,
                lubridate,
                stringi,
                openxlsx,
                openxlsx2,
                rhandsontable,
                shinycssloaders,
                shinyjs,
                zoo                
                
      strip: c("demo", "doc", "examples", "help", "html", "include", "tests", "vignette")
    permissions:
      contents: write
      repository-projects: read
